from amqp.exceptions import ConnectionError as ConnectionError
